spring:
  application:
    # 服务名
    name: demo-gateway
  cloud:
    discovery:
      enabled: true
    nacos:
      discovery:
        # 服务注册中心
        #        server-addr: 127.0.0.1:8848
        # server-addr: 10.152.183.100:8848 
        server-addr: nacos-0.nacos-headless:8848,nacos-1.nacos-headless:8848,nacos-2.nacos-headless:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: demo-provider
          uri: lb://demo-provider
          predicates:
            - Path=/p/**
          filters:
            - RewritePath=/p(?<segment>/?.*), $\{segment}
        - id: demo-consumer
          uri: lb://demo-consumer
          predicates:
            - Path=/c/**
          filters:
            - RewritePath=/c(?<segment>/?.*), $\{segment}


server:
  port: 8000

# management:
#   # 端点检查（健康检查）
#   endpoints:
#     web:
#       exposure:
#         include: "*"
