apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-provider
  labels:
    svc: demo
    app: provider
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: demo
      app: provider
  template:
    metadata:
      labels:
        svc: demo
        app: provider
    spec:
      containers:
      - name: demo-provider
        image: provider:0.1
        # imagePullPolicy: Always
        ports:
        - containerPort: 8010
        # resources:
        #   requests:
        #     memory: 1Gi
        #     cpu: 250m
        #   limits:
        #     memory: 1Gi
        #     cpu: 250m